FROM ubuntu:latest

RUN apt update -y 
RUN apt install openssh-server -y 

RUN apt install python3 -y 
RUN apt install python3-apt -y

RUN echo "root:1234" | chpasswd

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

RUN service ssh start

EXPOSE 22
EXPOSE 80

CMD ["/usr/sbin/sshd","-D"]
