FROM centos:7

RUN yum -y install openssh-server sudo nano epel-release openssl certmonger; systemctl enable sshd.service

RUN ssh-keygen -A

RUN echo "root:1234" | chpasswd

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

EXPOSE 22
EXPOSE 80

CMD ["/usr/sbin/sshd", "-D"]
