FROM registry.access.redhat.com/ubi8/ubi-init:latest

COPY ./CentOS-Stream-BaseOS.repo /etc/yum.repo.d/CentOS-Stream-BaseOS.repo

RUN yum -y install openssh-server sudo nano openssl ; systemctl enable sshd.service

RUN ssh-keygen -A

RUN echo "root:1234" | chpasswd

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

EXPOSE 22
EXPOSE 80

CMD ["/usr/sbin/sshd", "-D"]
